// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nudge-card/Refined.tsx": () => import("../components/mockups/nudge-card/Refined.tsx"),
  "./components/mockups/quick-add/Current.tsx": () => import("../components/mockups/quick-add/Current.tsx")
};
