import { db } from "../db";
import { siteContent } from "@shared/schema";
import { sql } from "drizzle-orm";

const POLICY_PAGES: { key: string; value: string }[] = [
  { key: "page-terms", value: "{\"title\":\"Terms & Conditions\",\"lastUpdated\":\"February 2026\",\"sections\":[{\"heading\":\"1. Introduction\",\"body\":\"Welcome to TurtleLittle. These Terms & Conditions govern your use of our website turtlelittle.com and the purchase of our products. By accessing our website or placing an order, you agree to be bound by these terms. Please read them carefully before using our services.\"},{\"heading\":\"2. Products & Personalisation\",\"body\":\"TurtleLittle offers personalised embroidered towels, blankets, and bathrobes. All personalisation details (names, initials or any other text) provided by the customer must be accurate. We are not responsible for errors in personalisation caused by incorrect information provided by the customer. Due to the personalised nature of our products, please double-check all details before confirming your order.\"},{\"heading\":\"3. Pricing & Payment\",\"body\":\"All prices are listed in Indian Rupees (INR) and are inclusive of applicable taxes unless stated otherwise. We reserve the right to change prices at any time without prior notice. Payment must be completed at the time of placing an order through our accepted payment methods. We use secure, industry-standard payment processing to protect your financial information.\"},{\"heading\":\"4. Orders & Confirmation\",\"body\":\"Once you place an order, you will receive an order confirmation. This confirmation does not guarantee acceptance of your order. We reserve the right to cancel or refuse any order for reasons including product availability, pricing errors, or suspected fraudulent activity. In such cases, you will be notified and any payment made will be refunded.\"},{\"heading\":\"5. Shipping & Delivery\",\"body\":\"We aim to dispatch all orders within 1-2 business days after order confirmation. During festive seasons or high-demand periods, processing may take slightly longer. Delivery timelines depend on your location and the shipping part...\"},{\"heading\":\"6. Returns & Refunds\",\"body\":\"Due to the personalised nature of our products, we generally do not accept returns or offer refunds unless the product is defective or incorrect. Please refer to our Refund & Cancellation Policy for details.\"},{\"heading\":\"7. Intellectual Property\",\"body\":\"All content on our website, including images, logos, text, and designs, is the property of TurtleLittle and is protected by applicable intellectual property laws. You may not reproduce, distribute, or use our content without prior written permission.\"},{\"heading\":\"8. Governing Law\",\"body\":\"These Terms & Conditions are governed by the laws of India. Any disputes arising from the use of our website or purchase of our products shall be subject to the exclusive jurisdiction of the courts in India.\"}]}" },
  { key: "page-refund", value: "{\"title\":\"Refund & Cancellation Policy\",\"lastUpdated\":\"February 2026\",\"sections\":[{\"heading\":\"1. Personalised Products\",\"body\":\"Since all TurtleLittle products are personalised with custom embroidery (names, initials, or specific designs), they are made-to-order and cannot be resold. Therefore, we do not accept returns or exchanges for change of mind, incorrect personalisation details provided by the customer, or size/colour preferences after the order has been placed.\"},{\"heading\":\"2. Eligible Returns\",\"body\":\"We accept returns and provide replacements or refunds only in the following cases:\\n• Manufacturing Defects: If the product has a defect in the fabric, stitching, or embroidery quality.\\n• Wrong Item: If you receive a product different from what you ordered.\\n• Damaged in Transit: If the product arrives damaged due to shipping.\"},{\"heading\":\"3. How to Request a Return\",\"body\":\"To initiate a return, please follow these steps:\\n1. Contact us within 48 hours of receiving your order via WhatsApp at +91 99900 79722 or email at hello@turtlelittle.com.\\n2. Share clear photographs of the product showing the defect or issue.\\n3. Include your order number and a brief description of the problem.\\n4. Our team will review your request and respond within 24-48 hours.\"},{\"heading\":\"4. Refund Process\",\"body\":\"Once your return request is approved, we will offer you the choice of a replacement product or a full refund. Refunds will be processed to the original payment method within 7-10 business days. For Cash on Delivery (COD) orders, refunds will be processed via bank transfer — we will collect your bank details securely.\"},{\"heading\":\"5. Order Cancellation\",\"body\":\"You may cancel your order within 2 hours of placing it by contacting us via WhatsApp or email. After this window, your order may already be in production and cannot be cancelled. For cancelled orders where payment was already made, refunds will be processed within 7-10 business days.\"}]}" },
  { key: "page-shipping", value: "{\"title\":\"Shipping Policy\",\"lastUpdated\":\"February 2026\",\"sections\":[{\"heading\":\"1. Processing Time\",\"body\":\"Since all TurtleLittle products are personalised with custom embroidery, each item is made-to-order. Orders typically take 1-2 business days to process and prepare for dispatch. During festive seasons or high-demand periods, processing may take slightly longer.\"},{\"heading\":\"2. Delivery Timeline\",\"body\":\"After dispatch, estimated delivery times are:\\n• Metro Cities (Delhi, Mumbai, Bangalore, Chennai, Kolkata, Hyderabad): 2-4 business days\\n• Other Cities & Towns: 4-7 business days\\n• Remote Areas: 7-10 business days\\n\\nPlease note that delivery timelines are estimates and may vary based on the shipping partner and your location. You will receive a shipping confirmation with tracking details once your order is dispatched.\"},{\"heading\":\"3. Shipping Charges\",\"body\":\"Shipping charges are calculated based on your order value and delivery location. Applicable charges will be displayed at checkout before you complete your purchase.\"},{\"heading\":\"4. Shipping Partners\",\"body\":\"We work with reputable logistics partners to ensure safe and timely delivery of your orders. All products are carefully packaged to protect the embroidery and fabric during transit.\"},{\"heading\":\"5. Order Tracking\",\"body\":\"Once your order is dispatched, you will receive a tracking number via WhatsApp or email. You can use this to track the real-time status of your delivery. If you haven't received tracking details within 5 business days of placing your order, please contact us.\"},{\"heading\":\"6. Delivery Issues\",\"body\":\"If your order has not arrived within the estimated delivery timeline, or if you receive a damaged package, please contact us immediately via WhatsApp at +91 99900 79722 or email at hello@turtlelittle.com. We will work with the shipping partner to resolve the issue as quickly as possible.\"}]}" },
  { key: "page-about", value: "{\"title\":\"About TurtleLittle\",\"lastUpdated\":\"February 2026\",\"sections\":[{\"heading\":\"Our Story\",\"body\":\"TurtleLittle was born from a simple idea — to create everyday essentials that feel personal, thoughtful, and special. What started as a passion for beautiful embroidery has grown into a brand that celebrates individuality through personalised luxury products.\\n\\nWe believe that the little things matter. A towel with your child's name, a blanket embroidered for a couple, a bathrobe that's uniquely yours — these small touches turn ordinary items into cherished keepsakes.\"},{\"heading\":\"What We Do\",\"body\":\"We specialise in premium quality embroidered towels, blankets, and bathrobes. Every product is made-to-order, personalised with names, initials, or custom designs that make each piece one-of-a-kind.\\n\\nFrom playful Disney characters for kids to elegant monograms for adults, our collections are designed to bring joy and a touch of luxury to everyday life.\"},{\"heading\":\"Our Promise\",\"body\":\"• Premium Quality: We use only the finest fabrics — 100% cotton terry, soft fleece, and luxurious velour — to ensure every product feels as good as it looks.\\n• Handcrafted with Love: Each item is carefully embroidered by skilled artisans who take pride in their craft.\\n• Personalised for You: No two products are the same. Every piece is made specifically for you or your loved ones.\\n• Customer First: We're committed to making your experience delightful, from browsing to unboxing.\"},{\"heading\":\"Why TurtleLittle?\",\"body\":\"The turtle represents patience, care, and attention to detail — values that are at the heart of everything we do. 'Little' reflects the small, meaningful touches that make our products special.\\n\\nTogether, TurtleLittle stands for thoughtful craftsmanship and personalised care.\"},{\"heading\":\"Get in Touch\",\"body\":\"We'd love to hear from you! Whether you have a question, a custom request, or just want to say hello, reach out to us via WhatsApp at +91 99900 79722 or email at hello@turtlelittle.com.\"}]}" },
  { key: "page-privacy", value: "{\"title\":\"Privacy Policy\",\"lastUpdated\":\"February 2026\",\"sections\":[{\"heading\":\"1. Introduction\",\"body\":\"TurtleLittle is committed to protecting your privacy. This Privacy Policy explains how we collect, use, store, and protect your personal information when you visit turtlelittle.com or purchase our products.\"},{\"heading\":\"2. Information We Collect\",\"body\":\"We collect the following types of information:\\n• Personal Information: Name, email address, phone number, shipping address, and billing address when you place an order.\\n• Personalisation Details: Names and initials you provide for embroidery on our products.\\n• Payment Information: Payment details are processed securely through our payment gateway partners and are not stored on our servers.\\n• Usage Data: Browser type, pages visited, time spent on pages, and other analytics data to improve our website experience.\\n• Cookies: We use cookies to maintain your cart, remember preferences, and improve your browsing experience.\"},{\"heading\":\"3. How We Use Your Information\",\"body\":\"• To process and fulfill your orders, including personalisation and delivery.\\n• To communicate with you about your orders, including shipping updates via WhatsApp or phone.\\n• To improve our website, products, and customer service.\\n• To send promotional communications (only with your consent, and you can opt out at any time).\\n• To prevent fraud and ensure the security of transactions.\"},{\"heading\":\"4. Information Sharing\",\"body\":\"We do not sell, trade, or rent your personal information to third parties. We may share your information only with:\\n• Shipping Partners: To deliver your orders.\\n• Payment Processors: To process your payments securely.\\n• Legal Requirements: When required by law or to protect our rights.\"},{\"heading\":\"5. Cookies\",\"body\":\"Our website uses cookies to enhance your experience. Cookies help us remember your cart items and preferences. You can disable cookies in your browser settings, but this may affect your shopping experience.\"},{\"heading\":\"6. Data Security\",\"body\":\"We implement industry-standard security measures to protect your personal information from unauthorised access, alteration, or disclosure. However, no method of internet transmission is 100% secure.\"},{\"heading\":\"7. Your Rights\",\"body\":\"You have the right to access, update, or request deletion of your personal information. Contact us at hello@turtlelittle.com for any privacy-related requests.\"},{\"heading\":\"8. Contact Us\",\"body\":\"If you have any questions about this Privacy Policy, please contact us at hello@turtlelittle.com or via WhatsApp at +91 99900 79722.\"}]}" },
];

export async function ensurePolicyPages() {
  let inserted = 0;
  for (const page of POLICY_PAGES) {
    const existing = await db.select({ key: siteContent.key }).from(siteContent).where(sql`${siteContent.key} = ${page.key}`);
    if (existing.length === 0) {
      await db.insert(siteContent).values({ key: page.key, value: page.value });
      inserted++;
      console.log(`Inserted policy page: ${page.key}`);
    }
  }
  if (inserted > 0) {
    console.log(`Policy pages migration: inserted ${inserted} pages.`);
  } else {
    console.log("Policy pages migration: all pages already exist.");
  }
}
